name: Renovate

on:
  schedule:
  # Run every Monday at 5:00 AM UTC
    - cron: '0 5 * * 1'
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
        - info
        - debug
        - trace
      dry_run:
        description: 'Dry run (no PRs will be created)'
        required: false
        default: false
        type: boolean
      force_refresh:
        description: 'Force refresh all dependencies'
        required: false
        default: false
        type: boolean

permissions:
  contents: write # To create branches and commits
  pull-requests: write # To create and update pull requests
  issues: write # For dependency dashboard (if enabled)
  checks: read # To read check status
  statuses: read # To read commit statuses
  actions: read # To read workflow runs
  security-events: read # To read security events

jobs:
  renovate:
    uses: resizes/github-actions/.github/workflows/renovate.yml@v1.4.4
    with:
      log_level: ${{ inputs.log_level || 'info' }}
      dry_run: ${{ inputs.dry_run || false }}
      force_refresh: ${{ inputs.force_refresh || false }}
      runner: 'ubuntu-latest'
      github_app_id: '2169914'
      owner: 'Resizes'
      repositories: |
        ${{ github.event.repository.name }}
    secrets:
      github_app_private_key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
  
  send_to_dc:
    needs: renovate
    runs-on: ubuntu-latest
    if: ${{ needs.renovate.outputs.pr_count != '0' }}
    steps:
      - name: Send Discord message
        uses: resizes/github-actions/discord/post-renovate@v1.4.4
        with:
          pr_count: ${{ needs.renovate.outputs.pr_count }}
          repository: ${{ github.repository }}
          discord_channel_id: ${{ secrets.RENOVATE_UPDATE_DISCORD_CHANNEL_ID }}
          discord_bot_token: ${{ secrets.RENOVATE_APP_BOT_DISCORD_TOKEN }}
